model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan2.HierarchicalVQModel
  params:
    embed_dim: 64
    n_embed: [128, 256, 512]
    num_stages: 3
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      residual_units: 64
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqvae2loss.VQLPIPSWithDiscriminator
      params:
        codebook_weight: [0.25, 0.25, 0.25]
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 30001
        disc_weight: 0.8

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 6
    num_workers: 8
    train:
      target: taming.data.faceshq.FacesHQTrain
      params:
        size: 1024
        crop_size: 256
    validation:
      target: taming.data.faceshq.FacesHQValidation
      params:
        size: 1024
        crop_size: 256
