model:
  base_learning_rate: 4.5e-06
  target: taming.models.cond_transformer.Net2NetTransformer
  params:
    cond_stage_key: coord
    transformer_config:
      target: taming.modules.transformer.mingpt.GPT
      params:
        vocab_size: 512
        block_size: 256
        n_layer: 24
        n_head: 16
        n_embd: 512
    first_stage_config:
      target: taming.models.vqgan.VQModel
      params:
        ckpt_path: logs/2023-09-25T05-40-28_ffhq256_vqgan/testtube/version_1/checkpoints/epoch=39.ckpt
        embed_dim: 64
        n_embed: 512
        ddconfig:
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
        lossconfig:
          target: taming.modules.losses.DummyLoss
    cond_stage_config:
      target: taming.modules.misc.coord.CoordStage
      params:
        n_embed: 1024
        down_factor: 16

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 30
    num_workers: 8
    train:
      target: taming.data.faceshq.FFHQ256Train
      params:
        size: 256
    validation:
      target: taming.data.faceshq.FFHQ256Validation
      params:
        size: 256